main: main.c plus.o minus.o times.o divide.o
	gcc main.c plus.o minus.o times.o divide.o -o calculator
plus.o: plus.c
	gcc -c plus.c
minus.o: minus.c
	gcc -c minus.c
times.o: times.c
	gcc -c times.c
divide.o: divide.c
	gcc -c divide.c 
